export const FETCH_BUILDINGS = 'FETCH_BUILDINGS'
export const FETCH_BUILDINGS_SUCCESS = 'FETCH_BUILDINGS_SUCCESS'
export const FETCH_BUILDINGS_FAILURE = 'FETCH_BUILDINGS_FAILURE'
export const FETCH_BUILDINGS_PENDING = 'FETCH_BUILDINGS_PENDING'

export const SET_ZOOMED = 'SET_ZOOMED'
export const SET_SELECTED = 'SET_SELECTED'
