export const FETCH_BUILDINGS = 'FETCH_BUILDINGS'
export const FETCH_BUILDINGS_SUCCESS = 'FETCH_BUILDINGS_SUCCESS'
export const FETCH_BUILDINGS_FAILURE = 'FETCH_BUILDINGS_FAILURE'
export const FETCH_BUILDINGS_PENDING = 'FETCH_BUILDINGS_PENDING'